### ISSUE TITLE
Question: Environment Setup

### ISSUE THREAD

**Issue by Yan-Muzi** [Ironprop-Stone/python-deepgate#3]
Hello,

I would like to use DeepGate2 to generate circuit embeddings for my task. Could you please tell me the versions of the packages that the code depends on, especially the ones related to PyTorch and CUDA?

I have already tried the requirements list from the DeepGate2 repository (https://github.com/Ironprop-Stone/DeepGate2/blob/main/requirements.txt), but it did not work. It seems that torch-scatter, torch-sparse cannot find .so files with "_cuda" suffix, which raises a NoneType exception. Neither upgrading nor downgrading these packages solved the problem.

Thank you very much!

**Comment by zshi0616** [comment]
Hi Muzi, 
We use torch 1.9.1 and cuda 10.2 to develop deepgate, the pyg package version is same as the link. You can have a try. 
Thanks!

**Comment by Yan-Muzi** [comment]
Thank you for your reply!

Unfortunately, several errors occur during my tries. The first one is that conda does not provide python 3.8.9 in the default channel now, so I install python 3.8.18 instead.

![image](https://github.com/Ironprop-Stone/python-deepgate/assets/107630641/14064f9f-3df7-40b4-9ed9-97eee6084497)

As shown below, the requirements.txt has some problems itself as well. The pytorch-transformers package occurs before the torch package, so pip can not resolve the dependency. In addition, torchvision 0.10.0 is conflicted with torch 1.9.1. I have to move pytorch-transformers below torch, and change torchvision to 0.10.1.

![image](https://github.com/Ironprop-Stone/python-deepgate/assets/107630641/44e087a9-59d1-41ac-84c0-542318616ebb)

There are two other packages needed that are not listed in requirements, which is py-aiger and progress. After installing them, I have the following error when pretraining the model.

![image](https://github.com/Ironprop-Stone/python-deepgate/assets/107630641/040e1ad2-cc85-4ea6-8885-50c913e3d910)

It seems that this error is due to the implementation of torch-sparse, and is fixed in the newer version. Similar error also occurs in torch-scatter. Upgrading these two packages does not work as newer versions are not supported by torch 1.9.1.

It would be greatly appreciated if you could offer some hints on how to solve this problem.
